language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x  ci/*
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; project example; compile; project core; test; package'
after_script:
- ci/sbt-deploy.sh
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: G4IWzFRapMps8pNTXbEsI3zRvKlYezU/aHVzj2f90Z9cIbnF0AtV2XdmRiOyWsB1SD5Dda2ekNygsZsFH8kITKga4eUp7B6ZN9985DdbUiW6R2ari8ns2Xj4ygaqc6AR1zEJHBdM2uIacj3Z3V2vAJjuoT9uqJKHXkr7c3yW7Yk=
